import { chromium } from "@playwright/test";
import assert from "node:assert/strict";
const browser = await chromium.launch(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE ? { executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE } : {});
try {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const page = await context.newPage();
  const errors = []; page.on("pageerror", e => errors.push(e.message));
  await page.goto(process.env.FARMASSIST_TEST_URL || "http://localhost:4173/farmassist/");
  await page.evaluate(async () => { await navigator.serviceWorker.ready; await caches.open("unrelated-app-cache"); });
  await page.waitForFunction(() => Boolean(navigator.serviceWorker.controller));
  const keys = await page.evaluate(async () => (await (await caches.open("joita-farmassist-v5")).keys()).map(request => new URL(request.url).pathname));
  assert(keys.some(key => key.endsWith(".js"))); assert(keys.some(key => key.endsWith(".css"))); assert(!keys.some(key => key.startsWith("/api/")));
  await context.setOffline(true);
  await page.reload();
  await page.getByRole("button", { name: "Toggle navigation" }).click(); await page.getByRole("navigation", { name: "FarmAssist modules" }).getByRole("link", {name:"Ask",exact:true}).click();
  await page.getByLabel("Answer language").selectOption("Hindi");
  await page.getByLabel("Your question", {exact:true}).fill("Mustard aphids at flowering. What should I inspect?");
  await page.getByRole("button", {name:"Ask FarmAssist",exact:true}).click();
  await page.locator(".advisory-result").waitFor();
  assert.match(await page.locator(".advisory-result").innerText(), /Offline KB/);
  assert.match(await page.locator(".advisory-result").innerText(), /कीट/);
  assert.equal(await page.locator(".answer-copy").getAttribute("lang"), "hi-IN");
  await page.reload(); await page.locator(".history-item").first().click(); assert.match(await page.locator(".advisory-result").innerText(), /कीट/);
  assert.equal(await page.getByLabel("Answer language").inputValue(), "Hindi");
  await page.getByRole("link", {name:"FarmAssist home",exact:true}).click();
  assert.equal(await page.getByRole("link", {name:"JOITA website",exact:true}).isVisible(), true);
  await page.getByRole("button",{name:"Toggle navigation",exact:true}).click();
  await page.getByRole("navigation",{name:"FarmAssist modules"}).getByRole("link",{name:"Calculators",exact:true}).click();
  await page.getByLabel("Field area",{exact:true}).fill("1"); await page.getByLabel("Area unit",{exact:true}).selectOption("Hectares");
  await page.getByRole("button",{name:"Calculate",exact:true}).click(); assert.match(await page.locator(".calculation-result").innerText(),/10,000/);
  await page.getByRole("button",{name:"Toggle navigation",exact:true}).click();
  await page.getByRole("navigation",{name:"FarmAssist modules"}).getByRole("link",{name:"Income & Costs",exact:true}).click();
  await page.getByLabel("Amount (INR)").fill("250.75"); await page.getByRole("button",{name:"Save transaction",exact:true}).click();
  await page.reload(); assert.match(await page.locator(".ledger-totals").innerText(),/250.75/);
  const savedCaches = await page.evaluate(() => caches.keys()); assert(savedCaches.includes("unrelated-app-cache")); assert.deepEqual(errors, []);
  await page.screenshot({path:"test-results/offline-mobile.png",fullPage:true,animations:"disabled"});
  console.log(JSON.stringify({offlineReload:true, offlineQuestion:true, offlineCalculators:true, offlineLedger:true, savedAnswerAfterReload:true, assetsCached:keys.length, apiNeverCached:true, unrelatedCachePreserved:true, browserErrors:errors}));
} finally { await browser.close(); }
